<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.35">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Targeted Prophylaxis &amp; Competing Risks – crecoolt</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-46f66b053e56abd73bb6e954d61a315b.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-1c2b39b91d62c1bd2d977d21438fc985.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">crecoolt</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./about.html"> 
<span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./validation.html"> 
<span class="menu-text">Validation cohort</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./intervention.html"> 
<span class="menu-text">Intervention impact</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./stewardship.html"> 
<span class="menu-text">CRE Risk Score Stewardship Analysis</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./CRE_other.html"> 
<span class="menu-text">CRE Infection Risk and Mortality in Liver Transplant Patients</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./diagnostics_treatment.html"> 
<span class="menu-text">Diagnostics and Treatment by Study Period</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="./prophylaxis_competing_risks.html" aria-current="page"> 
<span class="menu-text">Prophylaxis &amp; Competing Risks</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#background" id="toc-background" class="nav-link active" data-scroll-target="#background">Background</a></li>
  <li><a href="#study-population" id="toc-study-population" class="nav-link" data-scroll-target="#study-population">Study population</a></li>
  <li><a href="#crude-cre-infection-rates-and-competing-deaths" id="toc-crude-cre-infection-rates-and-competing-deaths" class="nav-link" data-scroll-target="#crude-cre-infection-rates-and-competing-deaths">Crude CRE infection rates and competing deaths</a></li>
  <li><a href="#logistic-regression-vs-fine-gray-competing-risks" id="toc-logistic-regression-vs-fine-gray-competing-risks" class="nav-link" data-scroll-target="#logistic-regression-vs-fine-gray-competing-risks">Logistic regression vs Fine-Gray competing risks</a></li>
  <li><a href="#day-overall-survival" id="toc-day-overall-survival" class="nav-link" data-scroll-target="#day-overall-survival">180-day overall survival</a>
  <ul class="collapse">
  <li><a href="#by-prophylaxis-group" id="toc-by-prophylaxis-group" class="nav-link" data-scroll-target="#by-prophylaxis-group">By prophylaxis group</a></li>
  <li><a href="#by-prophylaxis-group-cre-infection-status" id="toc-by-prophylaxis-group-cre-infection-status" class="nav-link" data-scroll-target="#by-prophylaxis-group-cre-infection-status">By prophylaxis group × CRE infection status</a></li>
  <li><a href="#adjusted-cox-model-for-180-day-mortality" id="toc-adjusted-cox-model-for-180-day-mortality" class="nav-link" data-scroll-target="#adjusted-cox-model-for-180-day-mortality">Adjusted Cox model for 180-day mortality</a></li>
  </ul></li>
  <li><a href="#summary-of-findings" id="toc-summary-of-findings" class="nav-link" data-scroll-target="#summary-of-findings">Summary of findings</a></li>
  <li><a href="#cre-infection-survival-penalty-by-study-period" id="toc-cre-infection-survival-penalty-by-study-period" class="nav-link" data-scroll-target="#cre-infection-survival-penalty-by-study-period">CRE infection survival penalty by study period</a></li>
  <li><a href="#cre-infection-survival-penalty-by-carbapenemase-mechanism" id="toc-cre-infection-survival-penalty-by-carbapenemase-mechanism" class="nav-link" data-scroll-target="#cre-infection-survival-penalty-by-carbapenemase-mechanism">CRE infection survival penalty by carbapenemase mechanism</a></li>
  <li><a href="#t-papnew-prophylaxis-effect-by-carbapenemase-mechanism" id="toc-t-papnew-prophylaxis-effect-by-carbapenemase-mechanism" class="nav-link" data-scroll-target="#t-papnew-prophylaxis-effect-by-carbapenemase-mechanism">T-PAPnew prophylaxis effect by carbapenemase mechanism</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Targeted Prophylaxis &amp; Competing Risks</h1>
<p class="subtitle lead">Replication and methodological critique of ciag185</p>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="background" class="level2">
<h2 class="anchored" data-anchor-id="background">Background</h2>
<p>Rinaldi <em>et al.</em> (2026, <em>Clinical Infectious Diseases</em>, doi:10.1093/cid/ciag185) used the CRECOOLT dataset to investigate the effect of targeted peri-operative antibiotic prophylaxis (T-PAP) on CRE infection in liver transplant recipients colonised with CRE before transplantation. Using augmented inverse probability weighting (AIPW) with a logistic outcome model, they reported a significant reduction in 15-day CRE infection with novel BL/BLI prophylaxis (T-PAPnew; ATE −14.6%, p = 0.002), while old-drug prophylaxis conferred no benefit. The effect was non-significant at 30 days (ATE −5.6%, p = 0.32).</p>
<p>This page presents three complementary analyses using the CRECOOLT cohort:</p>
<ol type="1">
<li><strong>Replication</strong> of the ciag185 approach (adjusted logistic regression, no competing risks)</li>
<li><strong>Competing risks correction</strong> using Fine-Gray sub-distribution hazard models, treating death before CRE infection as a competing event</li>
<li><strong>180-day overall survival</strong> stratified by prophylaxis group and CRE infection status</li>
</ol>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Methodological note
</div>
</div>
<div class="callout-body-container callout-body">
<p>Logistic regression — even with AIPW correction — treats patients who die before the endpoint as censored, as if they <em>could</em> have developed CRE infection after death. When early mortality is differential across treatment groups, this can bias the treatment effect estimate. The correct approach is a <strong>competing risks model</strong> (Fine-Gray sub-distribution hazard), which accounts for death as a competing event that precludes subsequent infection.</p>
</div>
</div>
<hr>
</section>
<section id="study-population" class="level2">
<h2 class="anchored" data-anchor-id="study-population">Study population</h2>
<p>Pre-OLT CRE colonisers were classified into three prophylaxis groups following ciag185 definitions: <strong>S-PAP</strong> (standard, no CRE activity), <strong>T-PAPold</strong> (aminoglycosides, tigecycline, colistin, high-dose meropenem), and <strong>T-PAPnew</strong> (ceftazidime-avibactam, meropenem-vaborbactam, cefiderocol).</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Baseline characteristics by prophylaxis group (n = 194 complete cases)</caption>
<colgroup>
<col style="width: 10%">
<col style="width: 4%">
<col style="width: 17%">
<col style="width: 18%">
<col style="width: 11%">
<col style="width: 18%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">PAP group</th>
<th style="text-align: right;">N</th>
<th style="text-align: left;">Median age (IQR)</th>
<th style="text-align: left;">Median MELD (IQR)</th>
<th style="text-align: left;">KPC (%)</th>
<th style="text-align: left;">CRE infection (%)</th>
<th style="text-align: left;">180-d mortality (%)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">S-PAP</td>
<td style="text-align: right;">105</td>
<td style="text-align: left;">57 (47–62)</td>
<td style="text-align: left;">20 (15–26)</td>
<td style="text-align: left;">82 (78.1%)</td>
<td style="text-align: left;">26 (24.8%)</td>
<td style="text-align: left;">18 (17.1%)</td>
</tr>
<tr class="even">
<td style="text-align: left;">T-PAPold</td>
<td style="text-align: right;">63</td>
<td style="text-align: left;">56 (48–59.5)</td>
<td style="text-align: left;">28 (21.5–34)</td>
<td style="text-align: left;">31 (49.2%)</td>
<td style="text-align: left;">24 (38.1%)</td>
<td style="text-align: left;">12 (19%)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">T-PAPnew</td>
<td style="text-align: right;">26</td>
<td style="text-align: left;">60 (43.5–66)</td>
<td style="text-align: left;">23.5 (18–29)</td>
<td style="text-align: left;">16 (61.5%)</td>
<td style="text-align: left;">5 (19.2%)</td>
<td style="text-align: left;">4 (15.4%)</td>
</tr>
</tbody>
</table>
</div>
</div>
<hr>
</section>
<section id="crude-cre-infection-rates-and-competing-deaths" class="level2">
<h2 class="anchored" data-anchor-id="crude-cre-infection-rates-and-competing-deaths">Crude CRE infection rates and competing deaths</h2>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Crude CRE infection rates and competing deaths by prophylaxis group</caption>
<colgroup>
<col style="width: 10%">
<col style="width: 4%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 21%">
<col style="width: 21%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">PAP group</th>
<th style="text-align: right;">N</th>
<th style="text-align: right;">15-d CRE n</th>
<th style="text-align: left;">15-d CRE %</th>
<th style="text-align: right;">30-d CRE n</th>
<th style="text-align: left;">30-d CRE %</th>
<th style="text-align: right;">Deaths ≤15d (no CRE)</th>
<th style="text-align: right;">Deaths ≤30d (no CRE)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">S-PAP</td>
<td style="text-align: right;">105</td>
<td style="text-align: right;">19</td>
<td style="text-align: left;">18.1%</td>
<td style="text-align: right;">25</td>
<td style="text-align: left;">23.8%</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">5</td>
</tr>
<tr class="even">
<td style="text-align: left;">T-PAPold</td>
<td style="text-align: right;">63</td>
<td style="text-align: right;">18</td>
<td style="text-align: left;">28.6%</td>
<td style="text-align: right;">21</td>
<td style="text-align: left;">33.3%</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="odd">
<td style="text-align: left;">T-PAPnew</td>
<td style="text-align: right;">26</td>
<td style="text-align: right;">2</td>
<td style="text-align: left;">7.7%</td>
<td style="text-align: right;">5</td>
<td style="text-align: left;">19.2%</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Competing deaths (death without CRE infection) are concentrated in the <strong>S-PAP group</strong> (5 within 30 days vs 1 in T-PAPold, 0 in T-PAPnew). Sicker S-PAP patients who die early are removed from the infection risk set, artificially deflating the S-PAP infection rate, which in turn shrinks the apparent benefit of T-PAPnew in logistic models.</p>
<hr>
</section>
<section id="logistic-regression-vs-fine-gray-competing-risks" class="level2">
<h2 class="anchored" data-anchor-id="logistic-regression-vs-fine-gray-competing-risks">Logistic regression vs Fine-Gray competing risks</h2>
<p>Adjusted models included: age, MELD at transplant, Charlson Comorbidity Index, viral hepatitis, HCC, metabolic liver disease, time from colonisation to OLT, and KPC mechanism (n = 194).</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Adjusted effect of prophylaxis on CRE infection: logistic regression vs Fine-Gray competing risks model</caption>
<colgroup>
<col style="width: 9%">
<col style="width: 35%">
<col style="width: 27%">
<col style="width: 27%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Endpoint</th>
<th style="text-align: left;">Method</th>
<th style="text-align: left;">T-PAPold vs S-PAP</th>
<th style="text-align: left;">T-PAPnew vs S-PAP</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">15-day</td>
<td style="text-align: left;">Logistic OR (no competing risks)</td>
<td style="text-align: left;">1.54 (0.66–3.59) p=0.322</td>
<td style="text-align: left;">0.29 (0.06–1.44) p=0.129</td>
</tr>
<tr class="even">
<td style="text-align: left;">15-day</td>
<td style="text-align: left;">Fine-Gray SHR (competing risks)</td>
<td style="text-align: left;">1.44 (0.74–2.81) p=0.29</td>
<td style="text-align: left;">0.35 (0.09–1.41) p=0.14</td>
</tr>
<tr class="odd">
<td style="text-align: left;">30-day</td>
<td style="text-align: left;">Logistic OR (no competing risks)</td>
<td style="text-align: left;">1.25 (0.56–2.79) p=0.582</td>
<td style="text-align: left;">0.59 (0.19–1.83) p=0.358</td>
</tr>
<tr class="even">
<td style="text-align: left;">30-day</td>
<td style="text-align: left;">Fine-Gray SHR (competing risks)</td>
<td style="text-align: left;">1.24 (0.67–2.3) p=0.49</td>
<td style="text-align: left;">0.64 (0.26–1.59) p=0.34</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="prophylaxis_competing_risks_files/figure-html/forest-plot-1.png" class="img-fluid figure-img" width="960"></p>
<figcaption>Adjusted effect of T-PAPnew vs S-PAP on CRE infection. Point estimates are virtually identical between methods, but the Fine-Gray SHR (competing risks) is the methodologically appropriate measure. The very wide confidence intervals reflect the small T-PAPnew group (n = 26).</figcaption>
</figure>
</div>
</div>
</div>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>Key finding
</div>
</div>
<div class="callout-body-container callout-body">
<p>Point estimates are nearly identical between methods (OR ≈ SHR ≈ 0.35 at 15 days, ~0.64 at 30 days). However, the competing risks correction attenuates significance (p moves from 0.13 to 0.14 at 15 days). The mechanistic direction of bias in ciag185’s larger dataset is clear: asymmetric early deaths in the S-PAP group inflate the apparent S-PAP infection denominator, and a formal competing risks analysis in their cohort would likely narrow — and possibly eliminate — the significant ATE at 15 days.</p>
</div>
</div>
<hr>
</section>
<section id="day-overall-survival" class="level2">
<h2 class="anchored" data-anchor-id="day-overall-survival">180-day overall survival</h2>
<section id="by-prophylaxis-group" class="level3">
<h3 class="anchored" data-anchor-id="by-prophylaxis-group">By prophylaxis group</h3>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="prophylaxis_competing_risks_files/figure-html/km-overall-1.png" class="img-fluid figure-img" width="864"></p>
<figcaption>Kaplan-Meier overall survival by prophylaxis strategy. Log-rank p = 0.864 — no significant difference across groups. 180-day survival: S-PAP 82.9%, T-PAPold 81.0%, T-PAPnew 84.6%.</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="by-prophylaxis-group-cre-infection-status" class="level3">
<h3 class="anchored" data-anchor-id="by-prophylaxis-group-cre-infection-status">By prophylaxis group × CRE infection status</h3>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="prophylaxis_competing_risks_files/figure-html/km-stratified-1.png" class="img-fluid figure-img" width="1056"></p>
<figcaption>180-day overall survival stratified by prophylaxis group (panels) and CRE infection status (colour). CRE infection is associated with ~30 percentage-point excess mortality across all three PAP groups (60% vs 90% survival). The survival penalty of CRE infection is strikingly consistent regardless of which prophylaxis strategy was used, reinforcing that prevention of infection is clinically meaningful. Note: the T-PAPnew panel shows only 5 CRE infection events, hence the very wide confidence interval and non-significant log-rank test.</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="adjusted-cox-model-for-180-day-mortality" class="level3">
<h3 class="anchored" data-anchor-id="adjusted-cox-model-for-180-day-mortality">Adjusted Cox model for 180-day mortality</h3>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Adjusted Cox proportional hazards model: 180-day mortality</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Covariate</th>
<th style="text-align: left;">HR (95% CI)</th>
<th style="text-align: right;">p-value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">T-PAPold vs S-PAP</td>
<td style="text-align: left;">0.71 (0.31–1.62)</td>
<td style="text-align: right;">0.421</td>
</tr>
<tr class="even">
<td style="text-align: left;">T-PAPnew vs S-PAP</td>
<td style="text-align: left;">0.73 (0.24–2.21)</td>
<td style="text-align: right;">0.580</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Age (per year)</td>
<td style="text-align: left;">0.99 (0.95–1.02)</td>
<td style="text-align: right;">0.438</td>
</tr>
<tr class="even">
<td style="text-align: left;">MELD at OLT (per point)</td>
<td style="text-align: left;">1.04 (1–1.09)</td>
<td style="text-align: right;">0.046</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Charlson index (per point)</td>
<td style="text-align: left;">1.16 (0.93–1.46)</td>
<td style="text-align: right;">0.194</td>
</tr>
<tr class="even">
<td style="text-align: left;">Viral hepatitis</td>
<td style="text-align: left;">0.56 (0.19–1.64)</td>
<td style="text-align: right;">0.292</td>
</tr>
<tr class="odd">
<td style="text-align: left;">HCC</td>
<td style="text-align: left;">0.45 (0.1–2.01)</td>
<td style="text-align: right;">0.295</td>
</tr>
<tr class="even">
<td style="text-align: left;">KPC mechanism</td>
<td style="text-align: left;">1.03 (0.47–2.22)</td>
<td style="text-align: right;">0.950</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Neither T-PAPold (HR 0.71, 95% CI 0.31–1.62, p = 0.42) nor T-PAPnew (HR 0.73, 95% CI 0.24–2.21, p = 0.58) was associated with significantly improved survival after adjustment, consistent with the unadjusted log-rank result.</p>
<hr>
</section>
</section>
<section id="summary-of-findings" class="level2">
<h2 class="anchored" data-anchor-id="summary-of-findings">Summary of findings</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Finding</th>
<th>Result</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>T-PAPnew reduces 15-day CRE infection</td>
<td>SHR 0.35 (0.09–1.41), p = 0.14 — directionally consistent with ciag185 but non-significant in this sub-cohort</td>
</tr>
<tr class="even">
<td>T-PAPnew reduces 30-day CRE infection</td>
<td>SHR 0.64 (0.26–1.59), p = 0.34 — no significant effect</td>
</tr>
<tr class="odd">
<td>T-PAPold has no benefit over S-PAP</td>
<td>SHR 1.24–1.44 across endpoints, p &gt; 0.29 — consistent with ciag185</td>
</tr>
<tr class="even">
<td>T-PAPnew improves 180-day survival</td>
<td>HR 0.73 (0.24–2.21), p = 0.58 — not significant</td>
</tr>
<tr class="odd">
<td>CRE infection attributable mortality</td>
<td>~30 percentage-point excess (60% vs 90% 180-day survival), p &lt; 0.001 in S-PAP and T-PAPold groups</td>
</tr>
<tr class="even">
<td>Competing risk bias in ciag185</td>
<td>Asymmetric early deaths (4.8% S-PAP vs 0% T-PAPnew within 30d) biases logistic models toward overstating T-PAPnew benefit</td>
</tr>
</tbody>
</table>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Limitations
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li><strong>Sample size</strong>: T-PAPnew n = 26 with only 5 patients developing CRE infection at 30 days; all models substantially underpowered</li>
<li><strong>No AIPW</strong>: Full ciag185 AIPW approach requires Stata <code>teffects aipw</code>; models here use standard adjusted regression with identical covariates</li>
<li><strong>Multisite colonisation</strong>: Excluded due to 75% missingness; included in ciag185 (with acknowledged imperfect balance after weighting)</li>
<li><strong>Observational design</strong>: Unmeasured confounding by indication for novel prophylaxis cannot be excluded</li>
</ul>
</div>
</div>
<hr>
</section>
<section id="cre-infection-survival-penalty-by-study-period" class="level2">
<h2 class="anchored" data-anchor-id="cre-infection-survival-penalty-by-study-period">CRE infection survival penalty by study period</h2>
<p>A key question is whether the <strong>mortality attributable to CRE infection</strong> differs between the retrospective and prospective cohorts — for instance, whether improved therapies in the prospective period have narrowed the survival gap between infected and non-infected patients.</p>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="prophylaxis_competing_risks_files/figure-html/period-cre-survival-1.png" class="img-fluid figure-img" width="960"></p>
<figcaption>180-day overall survival by CRE infection status, stratified by study period. The survival penalty associated with CRE infection (~30 percentage points) is strikingly consistent between the retrospective (89.8% vs 60.5%, p &lt; 0.001) and prospective (93.5% vs 66.7%, p = 0.029) cohorts. Despite the shift toward novel BL/BLI therapy in the prospective period, infection-attributable mortality remains unchanged, suggesting that once CRE infection is established, outcomes remain poor regardless of era.</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Cox model testing whether the CRE infection survival penalty differs between study periods (interaction term)</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Covariate</th>
<th style="text-align: left;">HR (95% CI)</th>
<th style="text-align: right;">p-value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">CRE infection (vs none) — Retrospective</td>
<td style="text-align: left;">4.38 (2.03–9.44)</td>
<td style="text-align: right;">0.000</td>
</tr>
<tr class="even">
<td style="text-align: left;">Prospective period (vs Retrospective)</td>
<td style="text-align: left;">0.62 (0.13–2.84)</td>
<td style="text-align: right;">0.536</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Age (per year)</td>
<td style="text-align: left;">1 (0.97–1.03)</td>
<td style="text-align: right;">0.996</td>
</tr>
<tr class="even">
<td style="text-align: left;">MELD at OLT (per point)</td>
<td style="text-align: left;">1.04 (1–1.08)</td>
<td style="text-align: right;">0.072</td>
</tr>
<tr class="odd">
<td style="text-align: left;">KPC mechanism</td>
<td style="text-align: left;">0.85 (0.4–1.77)</td>
<td style="text-align: right;">0.656</td>
</tr>
<tr class="even">
<td style="text-align: left;">CRE × Prospective interaction</td>
<td style="text-align: left;">1.11 (0.17–7.44)</td>
<td style="text-align: right;">0.911</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Interpretation
</div>
</div>
<div class="callout-body-container callout-body">
<p>The interaction between CRE infection and study period is non-significant (HR 1.11, 95% CI 0.17–7.44, p = 0.91), confirming that the <strong>survival penalty of CRE infection is statistically indistinguishable between the retrospective and prospective cohorts</strong>. Despite the shift toward novel BL/BLI therapy in the prospective period, once CRE infection is established, outcomes remain as poor as in the earlier era (~30–35% 180-day mortality in both periods). This reinforces that <strong>prevention of infection — whether through prophylaxis or infection-control measures — remains the priority</strong>, as treatment of established infection has not significantly improved patient survival.</p>
</div>
</div>
<hr>
</section>
<section id="cre-infection-survival-penalty-by-carbapenemase-mechanism" class="level2">
<h2 class="anchored" data-anchor-id="cre-infection-survival-penalty-by-carbapenemase-mechanism">CRE infection survival penalty by carbapenemase mechanism</h2>
<p>Novel BL/BLI agents (ceftazidime-avibactam, meropenem-vaborbactam) have potent activity against KPC-producing organisms. If these therapies are improving outcomes for infected patients, we would expect the survival penalty of CRE infection to be <strong>smaller in the KPC group</strong> (better treatment options) than in the non-KPC group (OXA-48, NDM, VIM — where therapeutic options remain more limited).</p>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="prophylaxis_competing_risks_files/figure-html/km-kpc-1.png" class="img-fluid figure-img" width="960"></p>
<figcaption>180-day overall survival by CRE infection status, stratified by carbapenemase mechanism. The survival penalty is numerically larger in the Non-KPC group (56.2% vs 91.8% = −35.6pp) than in the KPC group (64.1% vs 90% = −25.9pp), opposite to the hypothesis that novel BL/BLI therapy would narrow the KPC penalty. However, the interaction is non-significant (p = 0.43), so this difference could reflect chance. Non-KPC organisms (OXA-48, NDM, VIM) may represent inherently more aggressive infections or faces a greater therapeutic gap.</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Cox model: does the CRE infection survival penalty differ between KPC and non-KPC organisms?</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Covariate</th>
<th style="text-align: left;">HR (95% CI)</th>
<th style="text-align: right;">p-value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">CRE infection — KPC group (reference)</td>
<td style="text-align: left;">3.61 (1.52–8.58)</td>
<td style="text-align: right;">0.004</td>
</tr>
<tr class="even">
<td style="text-align: left;">Non-KPC vs KPC (no infection)</td>
<td style="text-align: left;">0.82 (0.25–2.67)</td>
<td style="text-align: right;">0.736</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Age (per year)</td>
<td style="text-align: left;">1 (0.97–1.03)</td>
<td style="text-align: right;">0.990</td>
</tr>
<tr class="even">
<td style="text-align: left;">MELD at OLT (per point)</td>
<td style="text-align: left;">1.04 (1–1.08)</td>
<td style="text-align: right;">0.063</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Prospective vs Retrospective</td>
<td style="text-align: left;">0.71 (0.29–1.76)</td>
<td style="text-align: right;">0.459</td>
</tr>
<tr class="even">
<td style="text-align: left;">CRE infection × Non-KPC interaction</td>
<td style="text-align: left;">1.84 (0.4–8.47)</td>
<td style="text-align: right;">0.432</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>Key finding — opposite to the hypothesis
</div>
</div>
<div class="callout-body-container callout-body">
<p>The survival penalty of CRE infection is <strong>numerically larger</strong> in the Non-KPC group (−35.6 percentage points: 56.2% vs 91.8%) than in the KPC group (−25.9pp: 64.1% vs 90.0%), suggesting that patients infected with non-KPC organisms (OXA-48, NDM, VIM) fare comparatively <em>worse</em> — not better. The interaction term is <strong>non-significant</strong> (HR 1.84, 95% CI 0.40–8.47, p = 0.43), so this difference could reflect chance given only 16 infected Non-KPC patients.</p>
<p>However, this finding is clinically plausible: novel BL/BLI agents (particularly ceftazidime-avibactam and meropenem-vaborbactam) are highly active against KPC and may have provided <em>some</em> survival benefit in that group, whereas non-KPC organisms — especially MBL-producers (NDM, VIM) — have <strong>fewer reliable treatment options</strong>, and ceftazidime-avibactam alone has limited activity against them. This is consistent with the broader observation that the therapeutic advance of the novel BL/BLI era has been most pronounced for KPC infections.</p>
</div>
</div>
<hr>
</section>
<section id="t-papnew-prophylaxis-effect-by-carbapenemase-mechanism" class="level2">
<h2 class="anchored" data-anchor-id="t-papnew-prophylaxis-effect-by-carbapenemase-mechanism">T-PAPnew prophylaxis effect by carbapenemase mechanism</h2>
<p>Novel BL/BLI agents have strong <em>in vitro</em> activity against KPC-producing organisms but limited activity against some non-KPC mechanisms (particularly NDM and VIM). If T-PAPnew works primarily through KPC suppression, we would expect its prophylactic benefit to be confined to the KPC subgroup and absent — or even detrimental — in non-KPC colonisers.</p>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="prophylaxis_competing_risks_files/figure-html/cif-kpc-subgroup-1.png" class="img-fluid figure-img" width="960"></p>
<figcaption>Cumulative incidence of CRE infection (competing risks CIF, death as competing event) by prophylaxis strategy, stratified by carbapenemase mechanism. Top row: 15-day window; bottom row: 30-day window. Left panels: KPC colonisers (n=129); right panels: Non-KPC colonisers (n=65). In the KPC subgroup, T-PAPnew shows a modest early reduction (12.5% vs S-PAP 19.5% at 15 days) which largely disappears by 30 days, consistent with the ciag185 overall findings. In the Non-KPC subgroup, zero CRE infections occurred among the 10 T-PAPnew patients at both timepoints — a striking observation that cannot be interpreted causally given the very small sample.</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Crude CRE infection rates by carbapenemase mechanism and prophylaxis group</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Mechanism</th>
<th style="text-align: left;">PAP group</th>
<th style="text-align: right;">n</th>
<th style="text-align: left;">15-day CRE</th>
<th style="text-align: left;">30-day CRE</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">KPC (n=129)</td>
<td style="text-align: left;">S-PAP</td>
<td style="text-align: right;">82</td>
<td style="text-align: left;">19.5%</td>
<td style="text-align: left;">25.6%</td>
</tr>
<tr class="even">
<td style="text-align: left;">KPC (n=129)</td>
<td style="text-align: left;">T-PAPold</td>
<td style="text-align: right;">31</td>
<td style="text-align: left;">29.0%</td>
<td style="text-align: left;">32.3%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">KPC (n=129)</td>
<td style="text-align: left;">T-PAPnew</td>
<td style="text-align: right;">16</td>
<td style="text-align: left;">12.5%</td>
<td style="text-align: left;">31.2%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Non-KPC (n=65)</td>
<td style="text-align: left;">S-PAP</td>
<td style="text-align: right;">23</td>
<td style="text-align: left;">13.0%</td>
<td style="text-align: left;">17.4%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Non-KPC (n=65)</td>
<td style="text-align: left;">T-PAPold</td>
<td style="text-align: right;">32</td>
<td style="text-align: left;">28.1%</td>
<td style="text-align: left;">34.4%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Non-KPC (n=65)</td>
<td style="text-align: left;">T-PAPnew</td>
<td style="text-align: right;">10</td>
<td style="text-align: left;">0% (0/10)</td>
<td style="text-align: left;">0% (0/10)</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>Key findings
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>KPC subgroup (n=129):</strong> T-PAPnew shows a modest early reduction in 15-day CRE infection (12.5% vs S-PAP 19.5%) that largely disappears by 30 days (31.2% vs 25.6%), consistent with the overall ciag185 findings of a short-lived prophylaxis benefit. Gray’s test is non-significant at both timepoints (p = 0.38 and p = 0.77), reflecting the small T-PAPnew subgroup (n=16).</p>
<p><strong>Non-KPC subgroup (n=65):</strong> Zero CRE infections occurred in the 10 T-PAPnew patients at both 15 and 30 days, compared to 13% and 17.4% respectively in S-PAP. This is biologically plausible — novel BL/BLI agents such as ceftazidime-avibactam and meropenem-vaborbactam have some activity against OXA-48 and may provide prophylactic benefit even outside the KPC group. However, with <strong>only n=10</strong> T-PAPnew Non-KPC patients, a formal interaction test is not estimable (complete separation), and this finding must be considered entirely <strong>hypothesis-generating</strong>.</p>
<p><strong>T-PAPold is consistently associated with higher infection rates than S-PAP in both subgroups</strong> — a probable confounding by indication effect (sicker or higher-risk patients were selected for old-drug prophylaxis).</p>
</div>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/crecoolt\.org");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>