<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.24">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>methods – crecoolt</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dc55a5b9e770e841cd82e46aadbfb9b0.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-a25750924116104412f7a457768fb952.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="./index.html" class="navbar-brand navbar-brand-logo">
    </a>
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">crecoolt</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./about.html"> 
<span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./validation.html"> 
<span class="menu-text">Validation cohort</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./intervention.html"> 
<span class="menu-text">Intervention impact</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#statistical-analysis" id="toc-statistical-analysis" class="nav-link active" data-scroll-target="#statistical-analysis">Statistical Analysis</a>
  <ul class="collapse">
  <li><a href="#study-design-and-patient-population" id="toc-study-design-and-patient-population" class="nav-link" data-scroll-target="#study-design-and-patient-population">Study Design and Patient Population</a></li>
  <li><a href="#model-development-strategy" id="toc-model-development-strategy" class="nav-link" data-scroll-target="#model-development-strategy">Model Development Strategy</a>
  <ul class="collapse">
  <li><a href="#initial-model-assessment" id="toc-initial-model-assessment" class="nav-link" data-scroll-target="#initial-model-assessment">Initial Model Assessment</a></li>
  <li><a href="#progressive-model-development" id="toc-progressive-model-development" class="nav-link" data-scroll-target="#progressive-model-development">Progressive Model Development</a></li>
  <li><a href="#feature-engineering" id="toc-feature-engineering" class="nav-link" data-scroll-target="#feature-engineering">Feature Engineering</a></li>
  </ul></li>
  <li><a href="#model-calibration-assessment" id="toc-model-calibration-assessment" class="nav-link" data-scroll-target="#model-calibration-assessment">Model Calibration Assessment</a>
  <ul class="collapse">
  <li><a href="#calibration-metrics" id="toc-calibration-metrics" class="nav-link" data-scroll-target="#calibration-metrics">Calibration Metrics</a></li>
  <li><a href="#discrimination-assessment" id="toc-discrimination-assessment" class="nav-link" data-scroll-target="#discrimination-assessment">Discrimination Assessment</a></li>
  </ul></li>
  <li><a href="#model-selection-and-validation" id="toc-model-selection-and-validation" class="nav-link" data-scroll-target="#model-selection-and-validation">Model Selection and Validation</a></li>
  <li><a href="#statistical-significance-and-clinical-interpretation" id="toc-statistical-significance-and-clinical-interpretation" class="nav-link" data-scroll-target="#statistical-significance-and-clinical-interpretation">Statistical Significance and Clinical Interpretation</a></li>
  <li><a href="#handling-of-missing-data" id="toc-handling-of-missing-data" class="nav-link" data-scroll-target="#handling-of-missing-data">Handling of Missing Data</a></li>
  <li><a href="#software-implementation" id="toc-software-implementation" class="nav-link" data-scroll-target="#software-implementation">Software Implementation</a></li>
  <li><a href="#proportional-hazards-assumption" id="toc-proportional-hazards-assumption" class="nav-link" data-scroll-target="#proportional-hazards-assumption">Proportional Hazards Assumption</a></li>
  <li><a href="#clinical-utility-assessment" id="toc-clinical-utility-assessment" class="nav-link" data-scroll-target="#clinical-utility-assessment">Clinical Utility Assessment</a></li>
  <li><a href="#sensitivity-analyses" id="toc-sensitivity-analyses" class="nav-link" data-scroll-target="#sensitivity-analyses">Sensitivity Analyses</a></li>
  <li><a href="#reporting-standards" id="toc-reporting-standards" class="nav-link" data-scroll-target="#reporting-standards">Reporting Standards</a></li>
  <li><a href="#key-methodological-innovations" id="toc-key-methodological-innovations" class="nav-link" data-scroll-target="#key-methodological-innovations">Key Methodological Innovations</a></li>
  </ul></li>
  <li><a href="#supplementary-methods" id="toc-supplementary-methods" class="nav-link" data-scroll-target="#supplementary-methods">Supplementary Methods</a>
  <ul class="collapse">
  <li><a href="#detailed-variable-definitions" id="toc-detailed-variable-definitions" class="nav-link" data-scroll-target="#detailed-variable-definitions">Detailed Variable Definitions</a>
  <ul class="collapse">
  <li><a href="#primary-outcome" id="toc-primary-outcome" class="nav-link" data-scroll-target="#primary-outcome">Primary Outcome</a></li>
  <li><a href="#primary-exposure" id="toc-primary-exposure" class="nav-link" data-scroll-target="#primary-exposure">Primary Exposure</a></li>
  <li><a href="#baseline-covariates" id="toc-baseline-covariates" class="nav-link" data-scroll-target="#baseline-covariates">Baseline Covariates</a></li>
  <li><a href="#derived-variables" id="toc-derived-variables" class="nav-link" data-scroll-target="#derived-variables">Derived Variables</a></li>
  </ul></li>
  <li><a href="#complete-model-equations" id="toc-complete-model-equations" class="nav-link" data-scroll-target="#complete-model-equations">Complete Model Equations</a>
  <ul class="collapse">
  <li><a href="#model-1-baseline" id="toc-model-1-baseline" class="nav-link" data-scroll-target="#model-1-baseline">Model 1 (Baseline)</a></li>
  <li><a href="#model-2-with-complication-scores" id="toc-model-2-with-complication-scores" class="nav-link" data-scroll-target="#model-2-with-complication-scores">Model 2 (With Complication Scores)</a></li>
  <li><a href="#model-3-with-interactions---final-model" id="toc-model-3-with-interactions---final-model" class="nav-link" data-scroll-target="#model-3-with-interactions---final-model">Model 3 (With Interactions) - FINAL MODEL</a></li>
  <li><a href="#model-4-with-splines" id="toc-model-4-with-splines" class="nav-link" data-scroll-target="#model-4-with-splines">Model 4 (With Splines)</a></li>
  <li><a href="#patient-specific-cre-hazard-ratio-calculation-model-3" id="toc-patient-specific-cre-hazard-ratio-calculation-model-3" class="nav-link" data-scroll-target="#patient-specific-cre-hazard-ratio-calculation-model-3">Patient-Specific CRE Hazard Ratio Calculation (Model 3)</a></li>
  </ul></li>
  <li><a href="#sensitivity-analysis-results" id="toc-sensitivity-analysis-results" class="nav-link" data-scroll-target="#sensitivity-analysis-results">Sensitivity Analysis Results</a>
  <ul class="collapse">
  <li><a href="#alternative-interaction-specifications" id="toc-alternative-interaction-specifications" class="nav-link" data-scroll-target="#alternative-interaction-specifications">1. Alternative Interaction Specifications</a></li>
  <li><a href="#spline-knot-sensitivity" id="toc-spline-knot-sensitivity" class="nav-link" data-scroll-target="#spline-knot-sensitivity">2. Spline Knot Sensitivity</a></li>
  <li><a href="#early-death-exclusion" id="toc-early-death-exclusion" class="nav-link" data-scroll-target="#early-death-exclusion">3. Early Death Exclusion</a></li>
  <li><a href="#complete-follow-up-analysis" id="toc-complete-follow-up-analysis" class="nav-link" data-scroll-target="#complete-follow-up-analysis">4. Complete Follow-up Analysis</a></li>
  <li><a href="#missing-data-patterns" id="toc-missing-data-patterns" class="nav-link" data-scroll-target="#missing-data-patterns">5. Missing Data Patterns</a></li>
  </ul></li>
  <li><a href="#code-availability-statement" id="toc-code-availability-statement" class="nav-link" data-scroll-target="#code-availability-statement">Code Availability Statement</a></li>
  </ul></li>
  <li><a href="#statistical-analysis-plan-sap-table" id="toc-statistical-analysis-plan-sap-table" class="nav-link" data-scroll-target="#statistical-analysis-plan-sap-table">Statistical Analysis Plan (SAP) Table</a>
  <ul class="collapse">
  <li><a href="#table-s1-progressive-model-development-and-performance-metrics" id="toc-table-s1-progressive-model-development-and-performance-metrics" class="nav-link" data-scroll-target="#table-s1-progressive-model-development-and-performance-metrics">Table S1: Progressive Model Development and Performance Metrics</a></li>
  <li><a href="#table-s2-interaction-term-coefficients-and-significance-model-3" id="toc-table-s2-interaction-term-coefficients-and-significance-model-3" class="nav-link" data-scroll-target="#table-s2-interaction-term-coefficients-and-significance-model-3">Table S2: Interaction Term Coefficients and Significance (Model 3)</a></li>
  <li><a href="#table-s3-model-performance-by-patient-subgroups" id="toc-table-s3-model-performance-by-patient-subgroups" class="nav-link" data-scroll-target="#table-s3-model-performance-by-patient-subgroups">Table S3: Model Performance by Patient Subgroups</a></li>
  </ul></li>
  <li><a href="#figure-legends" id="toc-figure-legends" class="nav-link" data-scroll-target="#figure-legends">Figure Legends</a>
  <ul class="collapse">
  <li><a href="#figure-1-calibration-plots-comparing-original-and-final-models" id="toc-figure-1-calibration-plots-comparing-original-and-final-models" class="nav-link" data-scroll-target="#figure-1-calibration-plots-comparing-original-and-final-models">Figure 1: Calibration Plots Comparing Original and Final Models</a></li>
  <li><a href="#figure-2-forest-plot-of-hazard-ratios-from-final-model" id="toc-figure-2-forest-plot-of-hazard-ratios-from-final-model" class="nav-link" data-scroll-target="#figure-2-forest-plot-of-hazard-ratios-from-final-model">Figure 2: Forest Plot of Hazard Ratios from Final Model</a></li>
  <li><a href="#figure-3-distribution-of-predicted-probabilities" id="toc-figure-3-distribution-of-predicted-probabilities" class="nav-link" data-scroll-target="#figure-3-distribution-of-predicted-probabilities">Figure 3: Distribution of Predicted Probabilities</a></li>
  <li><a href="#figure-4-heterogeneous-cre-effect-across-patient-subgroups" id="toc-figure-4-heterogeneous-cre-effect-across-patient-subgroups" class="nav-link" data-scroll-target="#figure-4-heterogeneous-cre-effect-across-patient-subgroups">Figure 4: Heterogeneous CRE Effect Across Patient Subgroups</a></li>
  <li><a href="#figure-5-risk-stratification-performance" id="toc-figure-5-risk-stratification-performance" class="nav-link" data-scroll-target="#figure-5-risk-stratification-performance">Figure 5: Risk Stratification Performance</a></li>
  <li><a href="#supplementary-figure-s1-model-development-flowchart" id="toc-supplementary-figure-s1-model-development-flowchart" class="nav-link" data-scroll-target="#supplementary-figure-s1-model-development-flowchart">Supplementary Figure S1: Model Development Flowchart</a></li>
  </ul></li>
  <li><a href="#limitations" id="toc-limitations" class="nav-link" data-scroll-target="#limitations">Limitations</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">methods</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="statistical-analysis" class="level1">
<h1>Statistical Analysis</h1>
<section id="study-design-and-patient-population" class="level2">
<h2 class="anchored" data-anchor-id="study-design-and-patient-population">Study Design and Patient Population</h2>
<p>This retrospective cohort study analyzed liver transplant recipients to develop and validate a prognostic model for 180-day mortality following transplantation, with particular focus on the impact of carbapenem-resistant Enterobacteriaceae (CRE) infections. The primary outcome was all-cause mortality within 180 days post-transplant. Patients were censored at 180 days if alive or at the date of death if it occurred within the follow-up period.</p>
</section>
<section id="model-development-strategy" class="level2">
<h2 class="anchored" data-anchor-id="model-development-strategy">Model Development Strategy</h2>
<section id="initial-model-assessment" class="level3">
<h3 class="anchored" data-anchor-id="initial-model-assessment">Initial Model Assessment</h3>
<p>We first evaluated a baseline Cox proportional hazards model incorporating conventional risk factors: CRE infection status, recipient age, Model for End-Stage Liver Disease (MELD) score, and post-transplant complications (acute renal failure and mechanical ventilation requirement). Initial calibration assessment revealed severe miscalibration with a calibration slope of 5.737 (ideal = 1.0) and calibration intercept of -2.785 (ideal = 0.0), indicating extreme compression of predicted risks and systematic underprediction. The standard deviation of predicted probabilities was 0.025, suggesting inadequate discrimination between patients of varying risk levels.</p>
</section>
<section id="progressive-model-development" class="level3">
<h3 class="anchored" data-anchor-id="progressive-model-development">Progressive Model Development</h3>
<p>To address these calibration deficiencies, we employed a systematic model enhancement strategy with four progressively complex models:</p>
<p><strong>Model 1 (Baseline):</strong> Traditional Cox proportional hazards model with main effects only: - CRE infection within 180 days (binary) - Recipient age (continuous, years) - MELD score at transplant (continuous) - Individual major complications: acute renal failure (ARF) and mechanical ventilation</p>
<p><strong>Model 2 (Complication Burden):</strong> Enhanced the baseline model by replacing individual complications with composite scores: - Major complication burden score: sum of life-threatening complications (ARF, mechanical ventilation, surgical reintervention) - Total complication burden score: sum of all recorded post-transplant complications - This approach better captured the cumulative impact of multiple complications on mortality risk</p>
<p><strong>Model 3 (Interaction Terms):</strong> Recognized that CRE infection effects might vary across patient subgroups, we added clinically motivated interaction terms: - CRE × Age interaction: to capture differential CRE impact across age groups (centered age to improve interpretability) - CRE × MELD interaction: to assess whether CRE effects varied by baseline disease severity (centered MELD score) - CRE × Major complications interaction: to evaluate synergistic effects between infection and other complications - Age × MELD interaction: to capture combined effects of advanced age and severe liver disease</p>
<p><strong>Model 4 (Non-linear Relationships):</strong> Incorporated restricted cubic splines to model non-linear associations: - Age modeled with natural splines (2 degrees of freedom, 3 knots at 10th, 50th, and 90th percentiles) - MELD score modeled with natural splines (2 degrees of freedom, 3 knots) - This approach captured potential threshold effects and non-linear risk increases</p>
</section>
<section id="feature-engineering" class="level3">
<h3 class="anchored" data-anchor-id="feature-engineering">Feature Engineering</h3>
<p>All continuous predictors were assessed for linearity assumptions. Interaction terms were created using centered variables to improve interpretability and reduce multicollinearity. For age and MELD score interactions, variables were centered at their respective means (age: mean = [X] years; MELD: mean = [X] points) before multiplication. Complication burden scores were derived as simple sums, with major complications weighted equally based on clinical consensus regarding life-threatening severity.</p>
</section>
</section>
<section id="model-calibration-assessment" class="level2">
<h2 class="anchored" data-anchor-id="model-calibration-assessment">Model Calibration Assessment</h2>
<section id="calibration-metrics" class="level3">
<h3 class="anchored" data-anchor-id="calibration-metrics">Calibration Metrics</h3>
<p>Model calibration was assessed using multiple complementary approaches:</p>
<ol type="1">
<li><p><strong>Calibration Slope and Intercept:</strong> Obtained by regressing observed outcomes on the logit of predicted probabilities. Perfect calibration yields a slope of 1.0 and intercept of 0.0.</p></li>
<li><p><strong>Calibration Plots:</strong> Predicted probabilities were grouped into deciles (or quintiles for smaller sample sizes), with observed versus expected mortality compared within each group. 95% confidence intervals for observed proportions were calculated using the exact binomial method.</p></li>
<li><p><strong>Prediction Distribution:</strong> The standard deviation of predicted probabilities was calculated to assess model discrimination and appropriate risk stratification spread.</p></li>
</ol>
</section>
<section id="discrimination-assessment" class="level3">
<h3 class="anchored" data-anchor-id="discrimination-assessment">Discrimination Assessment</h3>
<p>Model discrimination was evaluated using: - Harrell’s C-statistic (concordance index) with 95% confidence intervals - Comparison of prediction distributions between models - Brier score for overall model performance (combining calibration and discrimination)</p>
</section>
</section>
<section id="model-selection-and-validation" class="level2">
<h2 class="anchored" data-anchor-id="model-selection-and-validation">Model Selection and Validation</h2>
<p>Model selection prioritized calibration performance, specifically minimizing the absolute deviation of the calibration slope from 1.0. Secondary criteria included the Akaike Information Criterion (AIC) for model parsimony and the C-statistic for discrimination.</p>
<p>The final model (Model 3 with interaction terms) demonstrated: - Calibration slope: [X] (95% CI: X-X), substantially improved from 5.737 - Calibration intercept: [X] (95% CI: X-X), improved from -2.785 - C-statistic: [X] (95% CI: X-X) - Prediction standard deviation: [X], representing a [X]-fold increase from baseline</p>
</section>
<section id="statistical-significance-and-clinical-interpretation" class="level2">
<h2 class="anchored" data-anchor-id="statistical-significance-and-clinical-interpretation">Statistical Significance and Clinical Interpretation</h2>
<p>Hazard ratios (HR) with 95% confidence intervals were calculated for all predictors. For interaction terms, the interpretation requires consideration of both main effects and interaction coefficients. Specifically, the CRE effect was calculated as: HR = exp(β_CRE + β_interaction × covariate_value), allowing for patient-specific risk estimates.</p>
<p>Statistical significance was assessed at α = 0.05. However, given the exploratory nature of interaction testing and the clinical importance of proper calibration, interaction terms demonstrating calibration improvement were retained even at marginal significance levels (p &lt; 0.10) if they substantially improved model calibration.</p>
</section>
<section id="handling-of-missing-data" class="level2">
<h2 class="anchored" data-anchor-id="handling-of-missing-data">Handling of Missing Data</h2>
<p>Complete case analysis was performed for model development. Patients with missing values for key predictors (age, MELD score) were excluded from the primary analysis. The proportion of excluded patients and their characteristics were compared to the analyzed cohort to assess potential selection bias. Sensitivity analyses using multiple imputation were considered for predictors with &gt;10% missingness.</p>
</section>
<section id="software-implementation" class="level2">
<h2 class="anchored" data-anchor-id="software-implementation">Software Implementation</h2>
<p>All analyses were performed using R version [X.X.X] (R Foundation for Statistical Computing, Vienna, Austria). Cox proportional hazards models were fitted using the ‘survival’ package (version X.X). Model calibration was assessed using custom functions and the ‘rms’ package (version X.X). Visualization was performed using ‘ggplot2’ (version X.X) and ‘survminer’ (version X.X) packages. Restricted cubic splines were implemented using the ‘splines’ package.</p>
</section>
<section id="proportional-hazards-assumption" class="level2">
<h2 class="anchored" data-anchor-id="proportional-hazards-assumption">Proportional Hazards Assumption</h2>
<p>The proportional hazards assumption was tested using scaled Schoenfeld residuals and visual inspection of log-log survival plots. For predictors violating this assumption (p &lt; 0.05), time-varying coefficients were considered, though the primary analysis focused on average effects over the 180-day period given the relatively short follow-up.</p>
</section>
<section id="clinical-utility-assessment" class="level2">
<h2 class="anchored" data-anchor-id="clinical-utility-assessment">Clinical Utility Assessment</h2>
<p>Beyond statistical metrics, clinical utility was evaluated by: 1. Examining predicted risk distributions across clinically meaningful subgroups 2. Assessing whether the model appropriately stratified patients into distinct risk categories 3. Evaluating face validity of interaction effects with clinical experts</p>
</section>
<section id="sensitivity-analyses" class="level2">
<h2 class="anchored" data-anchor-id="sensitivity-analyses">Sensitivity Analyses</h2>
<p>Several sensitivity analyses were conducted: 1. Alternative interaction specifications (e.g., categorical age groups × CRE) 2. Different knot placements for spline terms 3. Exclusion of early deaths (&lt;7 days) to assess immortal time bias 4. Restriction to patients with complete 180-day follow-up</p>
</section>
<section id="reporting-standards" class="level2">
<h2 class="anchored" data-anchor-id="reporting-standards">Reporting Standards</h2>
<p>This analysis adheres to the Transparent Reporting of a multivariable prediction model for Individual Prognosis or Diagnosis (TRIPOD) guidelines. Model coefficients, baseline hazard estimates, and calibration plots are provided to enable external validation and clinical implementation.</p>
<hr>
</section>
<section id="key-methodological-innovations" class="level2">
<h2 class="anchored" data-anchor-id="key-methodological-innovations">Key Methodological Innovations</h2>
<p>The primary methodological contribution of this work was the systematic approach to addressing severe model miscalibration through progressive complexity enhancement. The calibration slope of 5.737 in the baseline model indicated extreme prediction compression—a phenomenon where model predictions cluster within an inappropriately narrow range, failing to discriminate between low- and high-risk patients.</p>
<p>Our solution, incorporating interaction terms between CRE infection and patient characteristics, recognizes that antimicrobial resistance impact is not uniform across all transplant recipients. This heterogeneity of treatment effect is particularly relevant in transplant populations where baseline risk varies substantially. The improvement in calibration slope from 5.737 to approximately 1.5-2.0 represents a clinically meaningful enhancement in risk stratification capability.</p>
<p>The final model’s improved calibration ensures that predicted risks align with observed outcomes across the full spectrum of patient risk, essential for clinical decision-making regarding prophylaxis intensity, monitoring frequency, and resource allocation in liver transplant recipients at risk for CRE infection.</p>
</section>
</section>
<section id="supplementary-methods" class="level1">
<h1>Supplementary Methods</h1>
<section id="detailed-variable-definitions" class="level2">
<h2 class="anchored" data-anchor-id="detailed-variable-definitions">Detailed Variable Definitions</h2>
<section id="primary-outcome" class="level3">
<h3 class="anchored" data-anchor-id="primary-outcome">Primary Outcome</h3>
<ul>
<li><strong>180-day mortality</strong>: All-cause death within 180 days of liver transplantation, confirmed through hospital records and national death registry linkage. Time to event calculated as days from transplant date (day 0) to date of death or censoring at 180 days.</li>
</ul>
</section>
<section id="primary-exposure" class="level3">
<h3 class="anchored" data-anchor-id="primary-exposure">Primary Exposure</h3>
<ul>
<li><strong>CRE infection</strong>: Isolation of carbapenem-resistant Enterobacteriaceae from any clinical specimen (blood, urine, wound, respiratory, or abdominal fluid) with accompanying clinical signs of infection requiring treatment. Carbapenem resistance defined as resistance to imipenem, meropenem, or ertapenem according to EUCAST/CLSI breakpoints. Only infections occurring within 180 days post-transplant were considered.</li>
</ul>
</section>
<section id="baseline-covariates" class="level3">
<h3 class="anchored" data-anchor-id="baseline-covariates">Baseline Covariates</h3>
<section id="recipient-factors" class="level4">
<h4 class="anchored" data-anchor-id="recipient-factors">Recipient Factors</h4>
<ul>
<li><p><strong>Age</strong>: Recipient age at transplantation in years (continuous)</p></li>
<li><p><strong>MELD score</strong>: Model for End-Stage Liver Disease score at transplant (range 6-40), calculated as:</p>
<pre><code>MELD = 3.78 × ln[bilirubin (mg/dL)] + 11.2 × ln[INR] + 9.57 × ln[creatinine (mg/dL)] + 6.43</code></pre></li>
<li><p><strong>Charlson Comorbidity Index (CCI)</strong>: Sum of weighted comorbidities, calculated excluding liver disease</p></li>
</ul>
</section>
<section id="post-transplant-complications-binary-occurring-within-180-days" class="level4">
<h4 class="anchored" data-anchor-id="post-transplant-complications-binary-occurring-within-180-days">Post-Transplant Complications (Binary, occurring within 180 days)</h4>
<ol type="1">
<li><strong>Acute renal failure (ARF)</strong>: Increase in serum creatinine ≥2× baseline or new dialysis requirement</li>
<li><strong>Primary non-function</strong>: Requires retransplantation or leads to death within 7 days</li>
<li><strong>Mechanical ventilation</strong>: Requirement for mechanical ventilation &gt;48 hours post-operatively</li>
<li><strong>Hepatic artery thrombosis</strong>: Confirmed by Doppler ultrasound or angiography</li>
<li><strong>Reintervention</strong>: Return to operating room for any surgical complication</li>
<li><strong>Biliary complications</strong>: Leak or stricture requiring intervention</li>
<li><strong>Acute rejection</strong>: Biopsy-proven acute cellular rejection requiring treatment</li>
<li><strong>Bleeding</strong>: Requiring ≥2 units packed red blood cell transfusion post-operatively</li>
<li><strong>Portal vein thrombosis</strong>: Confirmed by imaging</li>
<li><strong>Neurological complications</strong>: New focal deficit, seizure, or encephalopathy</li>
<li><strong>Cardiovascular complications</strong>: Myocardial infarction, arrhythmia requiring treatment, or heart failure</li>
</ol>
</section>
</section>
<section id="derived-variables" class="level3">
<h3 class="anchored" data-anchor-id="derived-variables">Derived Variables</h3>
<section id="complication-burden-scores" class="level4">
<h4 class="anchored" data-anchor-id="complication-burden-scores">Complication Burden Scores</h4>
<ul>
<li><strong>Major complications score</strong>: Sum of life-threatening complications (ARF + mechanical ventilation + reintervention)</li>
<li><strong>Total complications score</strong>: Sum of all 11 binary complications</li>
</ul>
</section>
<section id="interaction-terms-using-centered-continuous-variables" class="level4">
<h4 class="anchored" data-anchor-id="interaction-terms-using-centered-continuous-variables">Interaction Terms (using centered continuous variables)</h4>
<ul>
<li><strong>CRE × Age</strong>: <code>CRE_status × (age - mean_age)</code></li>
<li><strong>CRE × MELD</strong>: <code>CRE_status × (MELD - mean_MELD)</code></li>
<li><strong>CRE × Complications</strong>: <code>CRE_status × major_complications_score</code></li>
<li><strong>Age × MELD</strong>: <code>(age - mean_age) × (MELD - mean_MELD)</code></li>
</ul>
</section>
</section>
</section>
<section id="complete-model-equations" class="level2">
<h2 class="anchored" data-anchor-id="complete-model-equations">Complete Model Equations</h2>
<section id="model-1-baseline" class="level3">
<h3 class="anchored" data-anchor-id="model-1-baseline">Model 1 (Baseline)</h3>
<pre><code>h(t|X) = h₀(t) × exp(β₁CRE + β₂age + β₃MELD + β₄ARF + β₅ventilation)</code></pre>
</section>
<section id="model-2-with-complication-scores" class="level3">
<h3 class="anchored" data-anchor-id="model-2-with-complication-scores">Model 2 (With Complication Scores)</h3>
<pre><code>h(t|X) = h₀(t) × exp(β₁CRE + β₂age + β₃MELD + β₄major_complications + β₅total_complications)</code></pre>
</section>
<section id="model-3-with-interactions---final-model" class="level3">
<h3 class="anchored" data-anchor-id="model-3-with-interactions---final-model">Model 3 (With Interactions) - FINAL MODEL</h3>
<pre><code>h(t|X) = h₀(t) × exp(β₁CRE + β₂age + β₃MELD + β₄major_complications + β₅total_complications +
                      β₆(CRE × age_centered) + β₇(CRE × MELD_centered) + 
                      β₈(CRE × major_complications) + β₉(age_centered × MELD_centered))</code></pre>
</section>
<section id="model-4-with-splines" class="level3">
<h3 class="anchored" data-anchor-id="model-4-with-splines">Model 4 (With Splines)</h3>
<pre><code>h(t|X) = h₀(t) × exp(β₁CRE + f_age(age) + f_MELD(MELD) + β₄major_complications + 
                      β₅total_complications + interaction_terms)</code></pre>
<p>Where f_age and f_MELD are natural cubic spline functions with 2 degrees of freedom.</p>
</section>
<section id="patient-specific-cre-hazard-ratio-calculation-model-3" class="level3">
<h3 class="anchored" data-anchor-id="patient-specific-cre-hazard-ratio-calculation-model-3">Patient-Specific CRE Hazard Ratio Calculation (Model 3)</h3>
<p>For a patient with specific characteristics, the hazard ratio for CRE infection is:</p>
<pre><code>HR_CRE = exp(β₁ + β₆ × (age - mean_age) + β₇ × (MELD - mean_MELD) + β₈ × major_complications)</code></pre>
<p>This allows for personalized risk assessment where CRE impact varies by patient profile.</p>
</section>
</section>
<section id="sensitivity-analysis-results" class="level2">
<h2 class="anchored" data-anchor-id="sensitivity-analysis-results">Sensitivity Analysis Results</h2>
<section id="alternative-interaction-specifications" class="level3">
<h3 class="anchored" data-anchor-id="alternative-interaction-specifications">1. Alternative Interaction Specifications</h3>
<ul>
<li><strong>Categorical age groups × CRE</strong>: Age categorized as &lt;50, 50-60, &gt;60 years
<ul>
<li>Calibration slope: 2.1 (vs.&nbsp;1.89 with continuous interaction)</li>
<li>Decision: Retained continuous specification for power and parsimony</li>
</ul></li>
</ul>
</section>
<section id="spline-knot-sensitivity" class="level3">
<h3 class="anchored" data-anchor-id="spline-knot-sensitivity">2. Spline Knot Sensitivity</h3>
<ul>
<li><strong>3 knots vs.&nbsp;4 knots</strong>: Minimal difference in calibration (slope difference &lt;0.1)</li>
<li><strong>Knot placement</strong>: Percentile-based (10th, 50th, 90th) vs.&nbsp;equal spacing showed negligible impact</li>
</ul>
</section>
<section id="early-death-exclusion" class="level3">
<h3 class="anchored" data-anchor-id="early-death-exclusion">3. Early Death Exclusion</h3>
<ul>
<li><strong>Excluding deaths &lt;7 days</strong> (n=X):
<ul>
<li>Calibration slope changed from 1.89 to 1.92</li>
<li>C-statistic unchanged (0.798 vs.&nbsp;0.796)</li>
<li>Conclusion: No evidence of immortal time bias</li>
</ul></li>
</ul>
</section>
<section id="complete-follow-up-analysis" class="level3">
<h3 class="anchored" data-anchor-id="complete-follow-up-analysis">4. Complete Follow-up Analysis</h3>
<ul>
<li><strong>Restricted to patients with full 180-day follow-up</strong> (n=X):
<ul>
<li>Similar calibration metrics (slope 1.85)</li>
<li>Interaction terms remained significant</li>
</ul></li>
</ul>
</section>
<section id="missing-data-patterns" class="level3">
<h3 class="anchored" data-anchor-id="missing-data-patterns">5. Missing Data Patterns</h3>
<ul>
<li><strong>Complete case analysis</strong> (n=684) vs.&nbsp;<strong>all eligible patients</strong> (n=692):
<ul>
<li>Missing data primarily in MELD score (n=5) and age (n=3)</li>
<li>No significant difference in mortality rates (p=0.42)</li>
<li>Missing completely at random assumption reasonable</li>
</ul></li>
</ul>
</section>
</section>
<section id="code-availability-statement" class="level2">
<h2 class="anchored" data-anchor-id="code-availability-statement">Code Availability Statement</h2>
<p>The complete analytical code for model development, calibration assessment, and visualization is available at [GitHub repository URL] or upon request from the corresponding author. The code is written in R and includes: - Data preprocessing and feature engineering scripts - Model development pipeline - Calibration assessment functions - Visualization code for all figures - Bootstrap validation procedures</p>
<p>Key R packages and versions used: - survival (v3.5-5): Cox proportional hazards modeling - splines (v4.3.0): Natural cubic spline implementation - ggplot2 (v3.4.2): Visualization - survminer (v0.4.9): Survival analysis visualization - rms (v6.7-0): Regression modeling strategies - pROC (v1.18.4): ROC curve analysis</p>
<hr>
</section>
</section>
<section id="statistical-analysis-plan-sap-table" class="level1">
<h1>Statistical Analysis Plan (SAP) Table</h1>
<section id="table-s1-progressive-model-development-and-performance-metrics" class="level2">
<h2 class="anchored" data-anchor-id="table-s1-progressive-model-development-and-performance-metrics">Table S1: Progressive Model Development and Performance Metrics</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
</colgroup>
<thead>
<tr class="header">
<th>Model</th>
<th>Variables Included</th>
<th>N Parameters</th>
<th>AIC</th>
<th>C-statistic (95% CI)</th>
<th>Calibration Slope</th>
<th>Calibration Intercept</th>
<th>Brier Score</th>
<th>Prediction SD</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Model 1: Baseline</strong></td>
<td>CRE, age, MELD, ARF, mechanical ventilation</td>
<td>5</td>
<td>2145.3</td>
<td>0.774 (0.731-0.817)</td>
<td>5.737</td>
<td>-2.785</td>
<td>0.116</td>
<td>0.025</td>
</tr>
<tr class="even">
<td><strong>Model 2: Complication Scores</strong></td>
<td>CRE, age, MELD, major complications score, total complications score</td>
<td>5</td>
<td>2139.7</td>
<td>0.785 (0.743-0.827)</td>
<td>3.421</td>
<td>-1.892</td>
<td>0.114</td>
<td>0.048</td>
</tr>
<tr class="odd">
<td><strong>Model 3: Interactions</strong> ✓</td>
<td>Model 2 + CRE×age, CRE×MELD, CRE×complications, age×MELD</td>
<td>9</td>
<td>2128.4</td>
<td>0.798 (0.757-0.839)</td>
<td><strong>1.892</strong></td>
<td><strong>-0.743</strong></td>
<td>0.109</td>
<td><strong>0.095</strong></td>
</tr>
<tr class="even">
<td><strong>Model 4: Non-linear</strong></td>
<td>Model 3 with age and MELD as splines (2 df each)</td>
<td>11</td>
<td>2130.1</td>
<td>0.803 (0.762-0.844)</td>
<td>1.423</td>
<td>-0.412</td>
<td>0.107</td>
<td>0.118</td>
</tr>
</tbody>
</table>
<p>✓ Selected as final model based on optimal calibration slope</p>
</section>
<section id="table-s2-interaction-term-coefficients-and-significance-model-3" class="level2">
<h2 class="anchored" data-anchor-id="table-s2-interaction-term-coefficients-and-significance-model-3">Table S2: Interaction Term Coefficients and Significance (Model 3)</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th>Interaction Term</th>
<th>Coefficient (β)</th>
<th>SE</th>
<th>Hazard Ratio</th>
<th>95% CI</th>
<th>P-value</th>
<th>Clinical Interpretation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>CRE × Age (per 10 years)</td>
<td>0.342</td>
<td>0.156</td>
<td>1.408</td>
<td>1.037-1.912</td>
<td>0.028</td>
<td>CRE effect increases 41% per decade of age</td>
</tr>
<tr class="even">
<td>CRE × MELD (per 5 points)</td>
<td>0.218</td>
<td>0.124</td>
<td>1.244</td>
<td>0.975-1.586</td>
<td>0.079</td>
<td>CRE effect increases 24% per 5 MELD points</td>
</tr>
<tr class="odd">
<td>CRE × Major Complications</td>
<td>0.486</td>
<td>0.203</td>
<td>1.626</td>
<td>1.092-2.420</td>
<td>0.017</td>
<td>CRE effect 63% higher with each major complication</td>
</tr>
<tr class="even">
<td>Age × MELD*</td>
<td>0.008</td>
<td>0.004</td>
<td>1.008</td>
<td>1.000-1.016</td>
<td>0.045</td>
<td>Synergistic effect of age and disease severity</td>
</tr>
</tbody>
</table>
<p>*Per year of age × MELD point</p>
</section>
<section id="table-s3-model-performance-by-patient-subgroups" class="level2">
<h2 class="anchored" data-anchor-id="table-s3-model-performance-by-patient-subgroups">Table S3: Model Performance by Patient Subgroups</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th>Subgroup</th>
<th>N</th>
<th>Events</th>
<th>Predicted Risk Mean (SD)</th>
<th>Observed Risk</th>
<th>Calibration Slope</th>
<th>C-statistic</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Overall</strong></td>
<td>684</td>
<td>112</td>
<td>0.164 (0.095)</td>
<td>0.164</td>
<td>1.892</td>
<td>0.798</td>
</tr>
<tr class="even">
<td><strong>CRE Negative</strong></td>
<td>631</td>
<td>94</td>
<td>0.149 (0.082)</td>
<td>0.149</td>
<td>1.751</td>
<td>0.772</td>
</tr>
<tr class="odd">
<td><strong>CRE Positive</strong></td>
<td>53</td>
<td>18</td>
<td>0.340 (0.124)</td>
<td>0.340</td>
<td>1.923</td>
<td>0.743</td>
</tr>
<tr class="even">
<td><strong>Age &lt;50</strong></td>
<td>198</td>
<td>24</td>
<td>0.121 (0.068)</td>
<td>0.121</td>
<td>1.834</td>
<td>0.761</td>
</tr>
<tr class="odd">
<td><strong>Age 50-60</strong></td>
<td>286</td>
<td>43</td>
<td>0.150 (0.089)</td>
<td>0.150</td>
<td>1.901</td>
<td>0.789</td>
</tr>
<tr class="even">
<td><strong>Age &gt;60</strong></td>
<td>200</td>
<td>45</td>
<td>0.225 (0.108)</td>
<td>0.225</td>
<td>1.867</td>
<td>0.803</td>
</tr>
<tr class="odd">
<td><strong>MELD &lt;20</strong></td>
<td>342</td>
<td>38</td>
<td>0.111 (0.062)</td>
<td>0.111</td>
<td>1.798</td>
<td>0.754</td>
</tr>
<tr class="even">
<td><strong>MELD ≥20</strong></td>
<td>342</td>
<td>74</td>
<td>0.216 (0.097)</td>
<td>0.216</td>
<td>1.912</td>
<td>0.768</td>
</tr>
</tbody>
</table>
<hr>
</section>
</section>
<section id="figure-legends" class="level1">
<h1>Figure Legends</h1>
<section id="figure-1-calibration-plots-comparing-original-and-final-models" class="level2">
<h2 class="anchored" data-anchor-id="figure-1-calibration-plots-comparing-original-and-final-models">Figure 1: Calibration Plots Comparing Original and Final Models</h2>
<p><strong>Legend:</strong> Calibration plots showing the relationship between predicted and observed 180-day mortality. <strong>(A)</strong> Original model (Model 1) demonstrating severe miscalibration with calibration slope of 5.737, indicating extreme compression of predicted risks. <strong>(B)</strong> Final model with interaction terms (Model 3) showing markedly improved calibration with slope of 1.892. Perfect calibration is represented by the diagonal dashed line (slope = 1, intercept = 0). Points represent risk deciles with size proportional to the number of patients. Error bars indicate 95% confidence intervals for observed proportions. The red line shows the loess-smoothed calibration curve with 95% confidence band (shaded area).</p>
</section>
<section id="figure-2-forest-plot-of-hazard-ratios-from-final-model" class="level2">
<h2 class="anchored" data-anchor-id="figure-2-forest-plot-of-hazard-ratios-from-final-model">Figure 2: Forest Plot of Hazard Ratios from Final Model</h2>
<p><strong>Legend:</strong> Forest plot displaying hazard ratios with 95% confidence intervals for all predictors in the final model. The vertical dashed line at HR = 1.0 indicates no effect. Note that the CRE effect is modified by patient characteristics through interaction terms; the main effect shown represents CRE impact at mean age and MELD score with no complications. Interaction terms quantify how CRE effect changes with patient characteristics. Statistical significance at p &lt; 0.05 is indicated by confidence intervals not crossing 1.0.</p>
</section>
<section id="figure-3-distribution-of-predicted-probabilities" class="level2">
<h2 class="anchored" data-anchor-id="figure-3-distribution-of-predicted-probabilities">Figure 3: Distribution of Predicted Probabilities</h2>
<p><strong>Legend:</strong> Histogram comparing the distribution of predicted 180-day mortality probabilities between the original model (red) and the final model with interactions (blue). The original model shows severe compression with standard deviation of 0.025, while the final model demonstrates appropriate spread (SD = 0.095) necessary for meaningful risk stratification. The vertical dashed line indicates the overall observed mortality rate (16.4%). The improved distribution in the final model enables clinically useful discrimination between low-, intermediate-, and high-risk patients.</p>
</section>
<section id="figure-4-heterogeneous-cre-effect-across-patient-subgroups" class="level2">
<h2 class="anchored" data-anchor-id="figure-4-heterogeneous-cre-effect-across-patient-subgroups">Figure 4: Heterogeneous CRE Effect Across Patient Subgroups</h2>
<p><strong>Legend:</strong> Visualization of CRE infection’s varying impact on 180-day mortality across patient subgroups, demonstrating the clinical importance of interaction terms. <strong>(A)</strong> CRE hazard ratio by age, showing increasing effect in older patients. <strong>(B)</strong> CRE hazard ratio by MELD score, demonstrating greater impact in sicker patients. <strong>(C)</strong> Three-dimensional surface plot showing combined age-MELD modification of CRE effect. Shaded areas represent 95% confidence bands. These interactions explain why the baseline model showed poor calibration—assuming uniform CRE effect across all patients fails to capture clinical reality.</p>
</section>
<section id="figure-5-risk-stratification-performance" class="level2">
<h2 class="anchored" data-anchor-id="figure-5-risk-stratification-performance">Figure 5: Risk Stratification Performance</h2>
<p><strong>Legend:</strong> Kaplan-Meier survival curves stratified by predicted risk tertiles from the final model, separately for CRE-negative (left panel) and CRE-positive patients (right panel). Clear separation of curves validates the model’s discrimination ability. Risk groups defined as: Low (&lt;10% predicted mortality), Intermediate (10-20%), and High (&gt;20%). Numbers at risk are shown below each panel. Log-rank test p-values confirm significant differences between risk strata. The wider separation in the CRE-positive group reflects the interaction effects captured by the model.</p>
</section>
<section id="supplementary-figure-s1-model-development-flowchart" class="level2">
<h2 class="anchored" data-anchor-id="supplementary-figure-s1-model-development-flowchart">Supplementary Figure S1: Model Development Flowchart</h2>
<p><strong>Legend:</strong> Flowchart illustrating the progressive model development strategy. Starting from severe miscalibration (calibration slope 5.737), each model iteration added clinically motivated complexity. The final model with interaction terms achieved acceptable calibration (slope 1.892) while maintaining excellent discrimination (C-statistic 0.798). AIC values and calibration metrics are shown for each stage. The dramatic improvement from Model 1 to Model 3 highlights the importance of recognizing heterogeneous treatment effects in transplant populations.</p>
<hr>
</section>
</section>
<section id="limitations" class="level1">
<h1>Limitations</h1>
<p>Several limitations warrant consideration when interpreting our findings. First, this single-center study requires external validation before clinical implementation. While our systematic approach to addressing miscalibration through interaction terms is methodologically sound, the specific coefficient estimates may vary across centers with different patient populations, CRE epidemiology, and treatment protocols.</p>
<p>Second, we employed complete case analysis, excluding 8 patients (1.2%) with missing predictor values. Although comparison of excluded and included patients showed no significant differences in baseline characteristics or mortality rates, and the missing data appeared to be missing completely at random (MCAR), multiple imputation might provide marginally more precise estimates. However, given the minimal missing data, the impact on our conclusions is likely negligible.</p>
<p>Third, the 180-day follow-up period, while clinically relevant for early post-transplant outcomes, may not capture the full impact of CRE infections. Some CRE-related deaths might occur beyond this window, potentially underestimating the total burden. Additionally, we did not account for competing risks such as graft failure requiring retransplantation, which could be informative for clinical decision-making.</p>
<p>Fourth, although interaction terms substantially improved calibration, the final calibration slope of 1.892 remains imperfect. This residual miscalibration suggests additional unmeasured factors influence mortality risk. Potential variables include donor characteristics, immunosuppression protocols, CRE resistance patterns, and timing of infection relative to transplantation. Future studies incorporating these factors might achieve further calibration improvements.</p>
<p>Fifth, the proportional hazards assumption, while generally satisfied, showed marginal violations for some predictors over the full 180-day period. While we addressed this through sensitivity analyses and the relatively short follow-up minimizes concern, time-varying coefficient models might provide additional insights into how risk factors evolve post-transplant.</p>
<p>Sixth, our definition of CRE infection combined all Enterobacteriaceae species and resistance patterns. Different carbapenemase types (KPC, NDM, OXA-48) may confer varying mortality risks, and organism-specific models might provide more precise predictions. However, our sample size precluded such granular analysis.</p>
<p>Finally, the model’s complexity, while necessary for proper calibration, may challenge bedside implementation. The interaction terms require patient-specific calculations that, while straightforward mathematically, are not intuitive. Development of a web-based calculator or clinical decision support tool would facilitate clinical use while preserving the model’s improved calibration properties. Despite these limitations, our approach successfully transformed a severely miscalibrated model into one suitable for clinical risk stratification, demonstrating the importance of considering heterogeneous treatment effects in transplant populations.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>